# Generated by Django 5.1.1 on 2024-11-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colecao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colecao',
            old_name='livros',
            new_name='livro',
        ),
    ]
